name:                nparzzle
version:             0.1.0.0
github:              "githubuser/nparzzle"
license:             BSD-3-Clause
author:              "Kimberly Tsao"
maintainer:          "example@example.com"
copyright:           "2023 Kimberly Tsao"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nparzzle#readme>

dependencies:
- base >= 4.7 && < 5
- pqueue >= 1.5.0.0
- split >= 0.2
- text >= 2.0
- vector >= 0.13.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  nparzzle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nparzzle

tests:
  nparzzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nparzzle
